global:
  repository: "PENDING"
backend:
  image:
    tag: backend
    pullPolicy: Always
  port: 5001
  replicas: 2
frontend:
  image:
    tag: frontend
    pullPolicy: Always
  port: 80
  replicas: 2
nexus:
  loadBalancerIP: "nexus-loadbalancer-ip"
