backend:
  image:
    repository: apex-nexus-nexus-repository-manager.apex-nexus.svc.cluster.local
    tag: backend
    pullPolicy: IfNotPresent
  port: 5001
  replicas: 2
frontend:
  image:
    repository: apex-nexus-nexus-repository-manager.apex-nexus.svc.cluster.local
    tag: frontend
    pullPolicy: IfNotPresent
  port: 80
  replicas: 2
nexus:
  loadBalancerIP: "nexus-loadbalancer-ip"
