apiVersion: v1
kind: Service
metadata:    
    name: {{ .Release.Name }}-backend-svc
    labels:
        workload: backend
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: {{ .Values.backend.port }}
          protocol: TCP
    selector:
        workload: backend
