apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Release.Name }}-back-deployment
  namespace: apex-app
  labels: 
    workload: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      workload: backend
  template:
    metadata:
      labels:
        workload: backend
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
        - name: backend-container
          image: "{{ .Values.global.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_access_secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_refresh_secret
            - name: SALTH
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: salt
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: CORS_ORIGIN
            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: JWT_ACCESS_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: JWT_REFRESH_EXPIRES_IN