apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-frontend-svc
    namespace: apex-app
    labels:
        workload: frontend
spec:
    type: ClusterIP
    ports: 
        - port: 80
          targetPort: {{ .Values.frontend.port }}
          protocol: TCP
    selector:
        workload: frontend
        
