apiVersion: v1
kind: Service
metadata:
  name: nexus-local-proxy 
  namespace: apex-app     
spec:
  type: ExternalName
  externalName: apex-nexus-nexus-repository-manager.apex-nexus.svc.cluster.local