name: "ci"

on:
  push:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: checkout code
        uses: actions/checkout@v4

      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('backend/package-lock.json') }}

      - name: install dependencies
        run: npm ci
        working-directory: ./backend

      - name: run tests
        run: npm test
        working-directory: ./backend
        env:
          DB_HOST: localhost
          DB_USER: test_user
          DB_PASS: test_pass
          TEST_DB_NAME: test_db
          DB_PORT: 5432
          SALT: 4
          JWT_ACCESS_SECRET: ci_access_secret
          JWT_REFRESH_SECRET: ci_refresh_secret
          JWT_ACCESS_EXPIRES_IN: 1h
          JWT_REFRESH_EXPIRES_IN: 14d

  frontend:
    runs-on: ubuntu-latest
    needs: ["backend"]
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: checkout code
        uses: actions/checkout@v4

      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('frontend/package-lock.json') }}

      - name: install
        run: npm ci
        working-directory: ./frontend

      - name: build
        run: npm run build
        working-directory: ./frontend

      - name: test
        run: npm run test:ci
        working-directory: ./frontend

  docker:
    runs-on: ubuntu-latest
    needs: ["frontend", "backend"]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: allow insecure registries
        run: |
          echo '{"insecure-registries": ["34.9.41.218:8082"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: login to nexus
        run: docker login 34.9.41.218:8082 -u admin -p admin123

      - name: build and push backend
        run: |
          docker build -t 34.9.41.218:8082/apex:backend ./backend
          docker push 34.9.41.218:8082/apex:backend

      - name: build and push frontend
        run: |
          docker build -t 34.9.41.218:8082/apex:frontend ./frontend
          docker push 34.9.41.218:8082/apex:frontend
